# Use the official Node.js image as the base image for app generation
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Expose the port on which your React app will run
EXPOSE 3000
