version: '3.7'

networks:
  app:
    driver: bridge

services:
  web:
    image: nginx:stable-alpine
    container_name: ip-management-webserver
    ports:
      - "8017:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - db
    networks:
      - app

  backend:
    container_name: ip-management-backend
    ports:
      - "9017:9000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    networks:
      - app

  db:
    image: mariadb
    container_name: ip-management-db
    restart: unless-stopped
    tty: true
    ports:
      - "3317:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app

  frontend:
    container_name: ip-management-frontend
    ports:
      - "3017:3000"
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8017/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app


